language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - yarn env:dev
  - yarn run prettier --check src
  - jest --coverage --silent && coveralls < coverage/lcov.info
