language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - yarn env:dev
  - yarn run prettier --check src
  - yarn eslint .
  - yarn run tsc --build tsconfig.json
  - jest --coverage --silent && coveralls < coverage/lcov.info
